# We use kaniko for building docker images
# More details: https://github.com/GoogleContainerTools/kaniko

steps:

  - id: "docker:continuous-integration"
    name: gcr.io/kaniko-project/executor:v0.16.0
    args: [
      "--dockerfile=dockerfiles/continuous-integration/Dockerfile",
      "--cache=true",
      "--destination=gcr.io/$PROJECT_ID/celo-oracle:continuous-integration-$COMMIT_SHA"
    ]
    waitFor: ['-']

options:
  machineType: 'N1_HIGHCPU_8'
  
timeout: 3000s
  