# adapted from https://github.com/CircleCI-Public/circleci-demo-react-native
# and https://github.com/facebook/react-native/blob/master/.circleci/config.yml

version: 2.1
reference:
  workspace: &workspace ~/src

orbs:
  azure-acr: circleci/azure-acr@0.2.1

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:20.11
  environment:
    # To avoid ENOMEM problem when running node
    NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - run: echo "SKIP"
  lint-checks:
    <<: *defaults
    steps:
      - run: echo "SKIP"

  general-test:
    <<: *defaults
    steps:
      - run: echo "SKIP"
workflows:
  celo-oracle-build:
    jobs:
      - install_dependencies
      - lint-checks:
          requires:
            - install_dependencies
      - general-test:
          requires:
            - install_dependencies
