---
name: Build and Push Image
on: 
  workflow_dispatch:
    inputs:
      build_tag:
        description: 'Build environment (staging|production)'     
        required: true
        default: 'staging'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: ${{ inputs.version_tag }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with: 
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: Configure Docker Client 
      run: |-
        gcloud auth configure-docker --quiet

    - name: Build and publish docker image
      run: ./build_and_publish.sh