name: 'CI'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
  push:
    branches:
      - 'main'

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11

      - name: Install dependencies
        run: 'yarn install --immutable'

      - name: Build packages
        run: yarn build

      - name: Run lint checks
        run: |
          yarn run prettify:diff
          yarn run lint
          yarn run lint:tests

      - name: Run tests
        run: yarn run test --maxWorkers 2
