name: "CI"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "feature/**"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: "yarn install --immutable"

      - name: Build packages
        run: yarn build

      - name: Check licenses
        run: yarn check-licenses

      - name: Run lint checks
        run: |
          yarn run prettify:diff
          yarn run lint
          yarn run lint:tests

      - name: "Add lint summary"
        run: |
          echo "## Lint" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Run tests
        run: yarn run test --maxWorkers 2

      - name: "Add test summary"
        run: |
          echo "## Tests" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
