name: 'CI'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
  push:
    branches:
      - 'main'

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v4'

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Run lint checks
        run: |
          pnpm run prettify:diff
          pnpm run lint
          pnpm run lint:tests

      - name: Run tests
        run: pnpm run test --maxWorkers 2
