name: Docker Push OIDC

on:
  workflow_dispatch:
    inputs:
    build_env:
      description: 'Build environment (staging|production)'
      required: true
      default: 'staging'
      type: string

jobs:
  Build-Celo-Oracle:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-oracle/providers/github-by-repos
      service-account: 'celo-oracle-images@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-oracle/celo-oracle
      tag: ${{ inputs.build_env }}
      context: .
      trivy: true
      trivy-timeout: 40m
